server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SahidAlom6900/environment-variable-repository.git   
          default-label: main
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
    
    
logging:
#  pattern:
#    file: %d [%thread] %cyan(%logger{15}) - %msg %n
  file:
    name: C:/Users/User/Documents/LogFile/config-server-log.log 
  level:
    root: WARN
    org:
      hibernate: ERROR   
    com:
      technoelevate:
        config: INFO    